### ISSUE TITLE
Usage of keyframes result in invalid CSS message.

### ISSUE THREAD

**Issue by svenvandescheur** [maykinmedia/postcss-selector-lint#1]
```scss
body {
  @keyframes spin {
    0% {
      transform: rotate(0deg);
    }
    100% {
      transform: rotate(360deg);
    }
  }
}
```

 > 🐶 Found invalid CSS rule (screen.scss:10602,3 "0%").
